/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Tube(props) {
  const { nodes, materials } = useGLTF("/models/CQ2a.glb");

  const activeGeometry = nodes[`PROFILE_CQ2${props.bore}`].geometry;
  const bodyLength = props.stroke;
  const appliedMaterial = materials.ALUMINUM;

  appliedMaterial.metalness = 0.7;
  appliedMaterial.roughness = 0.15;

  return (
    <mesh
      geometry={activeGeometry}
      material={appliedMaterial}
      scale-z={bodyLength}
      castShadow
    />
  );
}

// useGLTF.preload("/CQ2a.glb");
